import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./component/header";
import Footer from "./component/footer";

const  satoshi = localFont({
  src: "./fonts/Satoshim.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const ClashDisplay= localFont({
  src: "./fonts/ClashDisplay.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${ClashDisplay.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
